managedConfig:
  clouds:
    # Top level key -> name of the cloud
    kube-cloud:
      type: kubernetes
      # Pod templates
      templates:
        - name: kubeslave
          # Only JNLP slaves are supported
          image: odavid/jenkins-jnlp-slave:latest
          # Labels are mandatory!
          # Your pipeline jobs will need to use node(label){} in order to use this slave template
          labels:
            - k8s
            - kubeslave
          # Environment variables to pass to the slave container
          environment:
            DIND: 'true'
            DOCKER_DAEMON_ARGS: "--insecure-registry=35.205.28.253"

          privileged: 'true'

  tools:
    installations:
      maven-3.5.3:
        type: maven
        installers:
          - id: '3.5.3'

  artifactory:
    useCredentialsPlugin: true
    ## List of artifactory servers
    artifactoryServers:
    - serverId: local-artifactory
      artifactoryUrl: http://35.205.28.253
      # use credentialsId
      deployerCredentialsConfig:
        credentialsId: 'artifactory-login'
